In [161]:
import pandas as pd
import numpy as np
from joblib import dump

In [162]:
#Training a model
df = pd.read_csv(r'C:\Users\1\Documents\Lab1\uts_advdsi_2022_11\data\raw\2022_train.csv')

In [163]:
df.head()

Id  GP   MIN   PTS  FGM  FGA   FG%  3P Made  3PA   3P%  ...  FTA   FT%  \
0  3799  80  24.3   7.8  3.0  6.4  45.7      0.1  0.3  22.6  ...  2.9  72.1   
1  3800  75  21.8  10.5  4.2  7.9  55.1     -0.3 -1.0  34.9  ...  3.6  67.8   
2  3801  85  19.1   4.5  1.9  4.5  42.8      0.4  1.2  34.3  ...  0.6  75.7   
3  3802  63  19.1   8.2  3.5  6.7  52.5      0.3  0.8  23.7  ...  1.5  66.9   
4  3803  63  17.8   3.7  1.7  3.4  50.8      0.5  1.4  13.7  ...  0.5  54.0   

   OREB  DREB  REB  AST  STL  BLK  TOV  TARGET_5Yrs  
0   2.2   2.0  3.8  3.2  1.1  0.2  1.6            1  
1   3.6   3.7  6.6  0.7  0.5  0.6  1.4            1  
2   0.6   1.8  2.4  0.8  0.4  0.2  0.6            1  
3   0.8   2.0  3.0  1.8  0.4  0.1  1.9            1  
4   2.4   2.7  4.9  0.4  0.4  0.6  0.7            1  

[5 rows x 21 columns]

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Id           8000 non-null   int64  
 1   GP           8000 non-null   int64  
 2   MIN          8000 non-null   float64
 3   PTS          8000 non-null   float64
 4   FGM          8000 non-null   float64
 5   FGA          8000 non-null   float64
 6   FG%          8000 non-null   float64
 7   3P Made      8000 non-null   float64
 8   3PA          8000 non-null   float64
 9   3P%          8000 non-null   float64
 10  FTM          8000 non-null   float64
 11  FTA          8000 non-null   float64
 12  FT%          8000 non-null   float64
 13  OREB         8000 non-null   float64
 14  DREB         8000 non-null   float64
 15  REB          8000 non-null   float64
 16  AST          8000 non-null   float64
 17  STL          8000 non-null   float64
 18  BLK          8000 non-null   float64
 19  TOV   

In [165]:
sum(df.duplicated())

0

In [166]:
df.describe()

Id           GP          MIN          PTS          FGM  \
count   8000.00000  8000.000000  8000.000000  8000.000000  8000.000000   
mean    7798.50000    62.777875    18.576662     7.267088     2.807037   
std     2309.54541    17.118774     8.935263     4.318732     1.693373   
min     3799.00000    -8.000000     2.900000     0.800000     0.300000   
25%     5798.75000    51.000000    12.000000     4.100000     1.600000   
50%     7798.50000    63.000000    16.800000     6.300000     2.400000   
75%     9798.25000    74.000000    23.500000     9.500000     3.700000   
max    11798.00000   123.000000    73.800000    34.200000    13.100000   

               FGA          FG%      3P Made          3PA          3P%  ...  \
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000  ...   
mean      6.231212    44.608900     0.264525     0.816562    19.583700  ...   
std       3.584559     6.155453     0.384093     1.060964    16.003155  ...   
min       0.800000    21.300000    -1.100000    -3.100000   -38.500000  ...   
25%       3.600000    40.400000     0.000000     0.100000     8.400000  ...   
50%       5.400000    44.400000     0.300000     0.800000    19.500000  ...   
75%       8.100000    48.700000     0.500000     1.500000    30.600000  ...   
max      28.900000    67.200000     1.700000     4.700000    82.100000  ...   

               FTA          FT%         OREB         DREB          REB  \
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000   
mean      1.947788    71.365825     1.077838     2.168500     3.245300   
std       1.252352    10.430447     0.785670     1.392224     2.085154   
min       0.000000   -13.300000     0.000000     0.200000     0.300000   
25%       1.000000    65.000000     0.500000     1.100000     1.700000   
50%       1.700000    71.400000     0.900000     1.900000     2.800000   
75%       2.600000    77.500000     1.500000     2.900000     4.300000   
max      11.100000   168.900000     5.500000    11.000000    15.900000   

               AST          STL          BLK          TOV  TARGET_5Yrs  
count  8000.000000  8000.000000  8000.000000  8000.000000  8000.000000  
mean      1.624513     0.648687     0.245212     1.257763     0.833625  
std       1.355986     0.407626     0.821037     0.723270     0.372440  
min       0.000000     0.000000   -17.900000     0.100000     0.000000  
25%       0.700000     0.300000     0.100000     0.700000     1.000000  
50%       1.300000     0.600000     0.200000     1.100000     1.000000  
75%       2.200000     0.900000     0.400000     1.600000     1.000000  
max      12.800000     3.600000    18.900000     5.300000     1.000000  

[8 rows x 21 columns]

In [167]:
df.dtypes

Id               int64
GP               int64
MIN            float64
PTS            float64
FGM            float64
FGA            float64
FG%            float64
3P Made        float64
3PA            float64
3P%            float64
FTM            float64
FTA            float64
FT%            float64
OREB           float64
DREB           float64
REB            float64
AST            float64
STL            float64
BLK            float64
TOV            float64
TARGET_5Yrs      int64
dtype: object

In [168]:
y_mean = df[['TARGET_5Yrs']].mean()
y_mean

TARGET_5Yrs    0.833625
dtype: float64

In [169]:
y_shape = (len(df), 1)
y_base = np.full(y_shape, y_mean)
y_base

array([[0.833625],
       [0.833625],
       [0.833625],
       ...,
       [0.833625],
       [0.833625],
       [0.833625]])

In [170]:
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

In [171]:
print(mse(df['TARGET_5Yrs'], y_base, squared=False))
print(mae(df['TARGET_5Yrs'], y_base))

0.37241691606987987
0.27738871875


In [172]:
y = df[['TARGET_5Yrs']]

In [173]:
X = df.drop(['TARGET_5Yrs', 'Id'], axis=1)

In [174]:
from sklearn.preprocessing import StandardScaler

In [175]:
scaler = StandardScaler()

In [176]:
df = scaler.fit_transform(df)

In [177]:
df

array([[-1.73183431,  1.00610018,  0.6405738 , ..., -0.05507101,
         0.47321012,  0.44674394],
       [-1.7314013 ,  0.71400493,  0.36076599, ...,  0.43214835,
         0.1966711 ,  0.44674394],
       [-1.73096829,  1.29819543,  0.05857357, ..., -0.05507101,
        -0.90948499,  0.44674394],
       ...,
       [ 1.73096829,  1.29819543,  1.07707397, ..., -0.05507101,
         0.74974914,  0.44674394],
       [ 1.7314013 , -1.38908087, -1.21735002, ...,  0.06673383,
        -1.0477545 ,  0.44674394],
       [ 1.73183431, -0.80489037,  0.06976588, ..., -0.66409522,
         0.1966711 ,  0.44674394]])

In [178]:
from joblib import dump

In [179]:
dump(scaler, r'C:\Users\1\Documents\Lab1\uts_advdsi_2022_11\models\scaler.joblib')

['C:\\Users\\1\\Documents\\Lab1\\uts_advdsi_2022_11\\models\\scaler.joblib']

In [180]:
from sklearn.linear_model import LinearRegression

In [181]:
#Training iniotial regression model
reg1 = LinearRegression()

In [182]:
reg1.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [183]:
dump(reg1,  r'C:\Users\1\Documents\Lab1\uts_advdsi_2022_11\models\linear_reg1t.joblib')

['C:\\Users\\1\\Documents\\Lab1\\uts_advdsi_2022_11\\models\\linear_reg1t.joblib']

In [184]:
reg1.score(X, y)

0.07566711849921592

In [185]:
y_preds = reg1.predict(X)

In [186]:
print(mse(y, y_preds, squared=False))
print(mae(y, y_preds))

0.3580499362505166
0.2606798307878509


In [187]:
df_test = pd.read_csv(r'C:\Users\1\Documents\Lab1\uts_advdsi_2022_11\data\raw\2022_test.csv')

In [188]:
df_test

Id  GP   MIN   PTS  FGM   FGA   FG%  3P Made  3PA   3P%  FTM  FTA  \
0        0  56   9.1   4.0  1.6   3.7  43.7      0.1  0.3   7.3  0.7  1.2   
1        1  43  19.3  10.1  3.7   8.1  46.0      0.6  1.7  35.1  1.8  2.5   
2        2  82  33.9  11.3  4.9  10.6  45.6      0.5  1.9  44.8  1.8  2.7   
3        3  86  44.7  18.8  6.8  15.9  42.9      0.5  1.8  13.5  4.5  6.3   
4        4  58  12.3   4.7  1.6   4.0  40.0      0.5  1.7  38.7  1.1  1.3   
...    ...  ..   ...   ...  ...   ...   ...      ...  ...   ...  ...  ...   
3794  3794  84  21.2   8.7  3.4   6.7  50.2      0.0  0.0  -4.5  1.7  2.5   
3795  3795  49  16.3   6.4  2.9   6.6  44.4     -0.1 -0.4  19.8  1.0  1.9   
3796  3796  53   9.9   2.1  0.8   1.8  43.1     -0.4 -0.6   1.9  0.6  1.0   
3797  3797  89  38.3  14.5  5.4  11.8  45.2      0.5  1.2  24.7  2.5  2.9   
3798  3798  55  12.0   3.0  1.1   2.5  42.3      0.1  0.6  11.7  0.9  1.1   

       FT%  OREB  DREB  REB  AST  STL  BLK  TOV  
0     63.4   1.2   0.8  1.7  0.4  0.2  0.3  0.8  
1     75.3   0.5   0.9  1.5  3.5  0.6  0.0  1.8  
2     71.2   1.3   3.3  4.5  2.5  1.3  0.3  2.0  
3     70.9   1.5   3.2  5.0  4.1  0.9  0.1  3.6  
4     76.9   0.2   0.6  0.9  1.5  0.5 -0.4  0.9  
...    ...   ...   ...  ...  ...  ...  ...  ...  
3794  68.1   1.9   2.3  3.9  1.5  0.6  0.3  2.0  
3795  50.2   1.7   2.8  4.4  0.4  0.4  0.4  0.7  
3796  63.9   0.7   1.0  1.7  0.4  0.4  0.2  0.5  
3797  89.2   1.5   4.0  5.5  3.7  1.3  0.3  2.4  
3798  76.7   0.7   2.0  2.6  0.6  0.3  0.2  1.2  

[3799 rows x 20 columns]

In [189]:
X_test = df_test.drop(['Id'], axis=1)

In [190]:
y_test_preds = reg1.predict(X_test)

In [191]:
y_test_preds

array([[0.81882934],
       [0.7753499 ],
       [0.91636627],
       ...,
       [0.72397671],
       [0.96997598],
       [0.75186956]])

In [192]:
df_pred = pd.DataFrame(y_test_preds)

In [193]:
df_pred

0
0     0.818829
1     0.775350
2     0.916366
3     0.946116
4     0.746997
...        ...
3794  0.968870
3795  0.800794
3796  0.723977
3797  0.969976
3798  0.751870

[3799 rows x 1 columns]

In [158]:
df_pred.columns =['Target_5Yrs']

In [160]:
df_pred.to_csv(r'C:\Users\1\Documents\Lab1\uts_advdsi_2022_11\data\processed\Lab1_results.csv')